### ISSUE TITLE
Unsorted deadlines with chromium-based browsers

### ISSUE THREAD

**Issue by delsner** [tum-i4/deadlines#2]
This happens to me on both, Chrome and Brave, and causes the deadlines to be unsorted or rather incorrectly sorted:
![image](https://user-images.githubusercontent.com/5920521/111469034-841e0900-8726-11eb-82cc-b7f7389760f7.png)

On Firefox, everything works as expected.

**Comment by vauhochzett** [comment]
Should be fixed in master, please try it out! It was just buggy JavaScript that Firefox apparently ignored and Chrome failed on. See commit https://github.com/tum-i4/deadlines/commit/1f2bd25bc861418bf79dbbdb69f2c238ac21bc57

**Comment by delsner** [comment]
LGTM, thx!
